Add Spanish translation
rafaelvcaetano/melonDS-android pull request #1023
Opened 2022-12-04 21:45 UTC by BackpackXl

2022-12-05 22:55 UTC, rafaelvcaetano commented
Thanks for your amazing contribution! I see that there are still some strings left to translate, so take your time. Do let me know when you think you have finished!

2022-12-08 17:19 UTC, BackpackXl commented
There is a way to test the translation

2022-12-08 17:25 UTC, rafaelvcaetano commented
For now, the only way to test is it by making a local build on your machine. Then, you just need to set your device's language to Spanish and the app will appear in Spanish. You can find instructions on how to make a local build in the project's README.

But let me know if you don't know how to do it or have some issue. I may be able to arrange something! But I can already tell you that the app will crash when opening the General settings. To fix it, you will need to update your branch and remove the `theme_options` string array from your file.

2022-12-08 18:14 UTC, BackpackXl commented
Thank. I will try

2022-12-11 18:33 UTC, BackpackXl commented
translations are finished are fine

2022-12-15 00:56 UTC, rafaelvcaetano requested changes
I have some issues in your translations and one of them simple prevents the app from compiling. Do you think you could fix them?

Additionally, I have made some translation suggestions. I am not a native spanish speaker, but I deal with the spanish language every day so I like to think I know a thing or two :P Feel free to completely throw away my suggestions because they can be completely stupid.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>escondido</item>
Capitalization is wrong.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>inferior-central</item>
Capitalization is wrong.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>ninguno</item>
Capitalization is wrong, as well as in the string below.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>ninguno</item>
All strings in this array have wrong capitalization.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>ninguno</item>
Wrong capitalization in this string and the one below.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>retrato</item>
Wrong capitalization in this string and the one below.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>Centro de ajuste</item>
This translation has a name but the original text has a verb. What do you think about using "Ajuste al centro" instead? The same could apply to the same string in the `background_landscape_mode_options` array below.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>elasticidad</item>
Wrong capitalization, as well as in the same string in the array below.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +    <string name="no_dsiware_titles_installed">no tienes ningún título DSiWare instalado</string>
The capitalization in this string is incorrect, as well as in the string below.

2022-12-15 00:56 UTC, rafaelvcaetano commented on app/src/main/res/values-es/strings.xml
> +        <item>Ajuste correcto</item>
The proper translation here is likely to be "Ajuste a la derecha".

2022-12-15 04:47 UTC, BackpackXl commented on app/src/main/res/values-es/strings.xml
> +    <string name="dsiware_manager_setup">configuración</string>
I made more mistakes in forgetting to capitalize

2022-12-15 04:48 UTC, BackpackXl commented on app/src/main/res/values-es/strings.xml
> +    <string name="dsiware_manager_setup">configuración</string>
It's solved

2022-12-15 04:49 UTC, BackpackXl commented on app/src/main/res/values-es/strings.xml
> +    <string name="rewind_length">duración de rebobinado</string>
It's solved

2022-12-15 04:52 UTC, BackpackXl commented on app/src/main/res/values-es/strings.xml
> +    <string name="jit_not_supported">JIT compatible con dispositivos de 64 bits.</string>
It's true it looks better

2022-12-15 04:58 UTC, BackpackXl commented on app/src/main/res/values-es/strings.xml
> +    <string name="threaded_rendering">Renderizado de subprocesos</string>
makes more sense

2023-01-21 06:32 UTC, BackpackXl commented
I have already solved everything. If there are more errors I will not hesitate to fix it

2023-01-23 23:56 UTC, rafaelvcaetano commented
Everything looks good! Thanks for your amazing contribution!

2023-01-23 23:57 UTC, rafaelvcaetano approved these changes

2023-01-23 23:57 UTC, merged