Updated Spanish translation
rafaelvcaetano/melonDS-android pull request #1128
Opened 2023-03-05 19:05 UTC by BackpackXl

2023-09-04 22:04 UTC, rafaelvcaetano commented
Sorry about leaving this here for so long! I didn't want to give the work of constantly opening new PRs after every new string I added. But I think that all text changes for the next release are done. Or at least, I will try to avoid changing anything in that regard. If you still want to update the strings, I think now is the perfect time! And thanks for your effort!

2023-09-04 22:06 UTC, agatemosu reviewed
this is untranslated

2023-09-07 20:13 UTC, BackpackXl commented
Thank you for your response, now the translation is ready and looks decent.

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="error_rom_not_found">No se pudo encontrar ROM</string>
```suggestion
    <string name="error_rom_not_found">No se pudo encontrar la ROM</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="error_rom_not_found_info">No se ha encontrado la ROM seleccionada. Asegúrese de que la ROM seleccionada se encuentre en el directorio de búsqueda de la ROM actual.</string>
```suggestion
    <string name="error_rom_not_found_info">No se ha encontrado la ROM seleccionada. Asegúrate de que la ROM seleccionada se encuentre en el directorio de búsqueda de ROM actual.\n%1$s</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="rewind_time_seconds">%1$ss</string> <!-- Ex: 43.56s -->
```suggestion
    <string name="rewind_time_seconds">%1$s s</string> <!-- Ex: 43.56 s -->
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="rewind_time_minutes_seconds">%1$dm%2$ss</string> <!-- Ex: 2m37.93s -->
```suggestion
    <string name="rewind_time_minutes_seconds">%1$d m %2$s s</string> <!-- Ex: 2 m 37.93 s -->
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="achievements">Achievements</string>
```suggestion
    <string name="achievements">Logros</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="reset">Resetear</string>
```suggestion
    <string name="reset">Reestablecer</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="category_video">Video</string>
```suggestion
    <string name="category_video">Vídeo</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="category_video_summary">Filtro, Renderizado de subprocesos, contador de FPS</string>
```suggestion
    <string name="category_video_summary">Filtro, renderizado de subprocesos, contador de FPS</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="retroachievements">RetroAchievements</string> <!-- Unir las palabras porque este es el nombre oficial. -->
```suggestion
    <string name="retroachievements">RetroAchievements</string> <!-- Mantén las palabras unidas porque este es el nombre oficial -->
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="retroachievements_summary">Inicio de sesión &amp; Gestionar la conexión de RetroAchievements</string> <!-- Mantener las palabras juntas porque este es el nombre oficial -->
```suggestion
    <string name="retroachievements_summary">Inicio de sesión &amp; Gestionar la conexión de RetroAchievements</string> <!-- Mantén las palabras unidas porque este es el nombre oficial -->
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string nam e="cheats">Trucos</string>
```suggestion
    <string name="cheats">Trucos</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="rom_shortcut">Acceso directo a ROM</string>
```suggestion
    <string name="rom_shortcut">Acceso directo a la ROM</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="label_rom_config_load_gba_rom">Cargar ROM GBA</string>
```suggestion
    <string name="label_rom_config_load_gba_rom">Cargar ROM de GBA</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="label_rom_config_gba_rom_path">Ruta de acceso ROM GBA</string>
```suggestion
    <string name="label_rom_config_gba_rom_path">Ruta de acceso a la ROM de GBA</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="retro_achievements_tab">Retro Achievements</string> <!-- Mantenga las palabras separadas para ayudar con el ajuste de palabras -->
```suggestion
    <string name="retro_achievements_tab">Retro Achievements</string> <!-- Mantén las palabras separadas para ayudar con el ajuste de palabras -->
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="retroachievements_logout_confirmation">¿Estás seguro de que deseas cerrar sesión en RetroAchievements? No podrás desbloquear logros mientras juegas.</string>
```suggestion
    <string name="retroachievements_logout_confirmation">¿Estás seguro de que quieres cerrar sesión en RetroAchievements? No podrás desbloquear logros mientras juegas.</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="retro_achievements_relaunch_to_apply_settings">Reinicia el ROM para aplicar la nueva configuración de RetroAchievements</string>
```suggestion
    <string name="retro_achievements_relaunch_to_apply_settings">Reinicia la ROM para aplicar la nueva configuración de RetroAchievements</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="completed_achievements"><b>%1$d</b> de <b>%2$d</b> (%3$d%%)</string>
```suggestion
    <string name="completed_achievements"><b>%1$d</b> de <b>%2$d</b> (%3$d% %)</string>
```

2023-09-07 20:50 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="achievements_loaded">Achievements loaded</string>
```suggestion
    <string name="achievements_loaded">Logros cargados</string>
```

2023-09-11 11:58 UTC, agatemosu requested changes

2023-09-11 11:58 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="rewind_time_minutes_seconds">%1$dm%2$ss</string>
```suggestion
    <string name="rewind_time_seconds">%1$s s</string> <!-- Ej: 43,56 s -->
    <string name="rewind_time_minutes_seconds">%1$d min %2$s s</string> <!-- Ej: 2 min 37,93 s -->
```
?

2023-09-11 11:58 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="completed_achievements"><b>%1$d</b> de <b>%2$d</b> (%3$d%%)</string>
```suggestion
    <string name="completed_achievements"><b>%1$d</b> de <b>%2$d</b> (%3$d% %)</string>
```

2023-09-11 12:15 UTC, agatemosu requested changes

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="dsiware_manager_import_title_error_metadat_fetch_failed">No se pudo descargar los metadatos del título. Verifique su conexión a internet.</string>
```suggestion
    <string name="dsiware_manager_import_title_error_metadat_fetch_failed">No se pudieton descargar los metadatos del título. Verifica tu conexión a Internet.</string>
```

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +
```suggestion
    <string name="ellipsis">…</string>
```

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="dsiware_import_from_rom_list">De la lista de ROM</string>
```suggestion
    <string name="dsiware_import_from_rom_list">Desde la lista de ROM</string>
```

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="failed_reset_emulation">No se pudo restablecer</string>
```suggestion
    <string name="failed_reset_emulation">No se pudo restablecer la emulación</string>
```

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="rewind_unavailable_ra_hardcore_enabled">Rebobinado no disponible en modo Hardcore</string>
```suggestion
    <string name="rewind_unavailable_ra_hardcore_enabled">El rebobinado no disponible en modo Hardcore</string>
```

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>      <string name="background_add_processing_failed">Error al procesar la imagen de fondo seleccionada. Asegúrese de que no esté dañado.</string>
```suggestion
    <string name="background_add_processing_failed">Error al procesar la imagen de fondo seleccionada. Asegúrate de que no esté dañada.</string>
```

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="retroachievements_login_status">Has iniciado sesión como %1$s</string>
```suggestion
    <string name="retroachievements_login_status">Sesión iniciada como %1$s</string>
```

2023-09-11 12:15 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
>          <item>1.5x</item>
```suggestion
        <item>1,5x</item>
```

2023-09-12 02:21 UTC, BackpackXl commented
Thank you for improving and fixing!"

2023-09-12 05:04 UTC, agatemosu requested changes

2023-09-12 05:04 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="dsiware_manager_import_title_error_metadat_fetch_failed">No se pudieton descargar los metadatos del título. Verifica tu conexión a Internet.</string>
my typo
```suggestion
    <string name="dsiware_manager_import_title_error_metadat_fetch_failed">No se pudieron descargar los metadatos del título. Verifica tu conexión a Internet.</string>
```

2023-09-12 05:08 UTC, agatemosu requested changes

2023-09-12 05:08 UTC, agatemosu commented on app/src/main/res/values-b+es/strings.xml
> +    <string name="rewind_time_minutes_seconds">%1$d min %2$s s</string> <!-- Ej: 2 min 37,93 s -->
sorry
```suggestion
    <string name="rewind_time_seconds">%1$s s</string> <!-- Ej: 43,56 s -->
    <string name="rewind_time_minutes_seconds">%1$d min %2$s s</string> <!-- Ej: 2 min 37,93 s -->
```

2023-09-13 05:07 UTC, agatemosu approved these changes

2023-10-30 15:23 UTC, merged

2023-10-30 15:23 UTC, rafaelvcaetano commented
Thank you both for you amazing effort 🙂